apiVersion: batch/v1
kind: CronJob
metadata:
  name: sasya-engine-periodic-tests
  namespace: sasya-arogya
  labels:
    app: sasya-engine
    component: periodic-tests
spec:
  # Run every 2 hours
  schedule: "0 */2 * * *"
  # Keep successful jobs for 1 day
  successfulJobsHistoryLimit: 1
  # Keep failed jobs for 3 days for debugging
  failedJobsHistoryLimit: 3
  # Start deadline for the job
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      # Job timeout of 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: sasya-engine
            component: periodic-tests
        spec:
          restartPolicy: OnFailure
          containers:
          - name: periodic-tester
            image: python:3.11-slim
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash"]
            args: ["/app/run_periodic_tests.sh", "http://sasya-engine-service:8080"]
            env:
            - name: SASYA_ENGINE_URL
              value: "http://sasya-engine-service:8080"
            - name: MAX_TESTS_PER_CATEGORY
              value: "3"
            - name: NOTIFICATION_WEBHOOK
              value: ""  # Set this to your webhook URL if you want notifications
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            volumeMounts:
            - name: test-scripts
              mountPath: /app
            - name: test-results
              mountPath: /tmp/sasya_engine_tests
            - name: test-images
              mountPath: /app/resources/images_for_test
              readOnly: true
          volumes:
          - name: test-scripts
            configMap:
              name: sasya-engine-test-scripts
              defaultMode: 0755
          - name: test-results
            persistentVolumeClaim:
              claimName: sasya-engine-test-results
          - name: test-images
            configMap:
              name: sasya-engine-test-images
              defaultMode: 0644
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sasya-engine-test-scripts
  namespace: sasya-arogya
  labels:
    app: sasya-engine
    component: periodic-tests
data:
  test_engine_periodic.py: |
    # Content of test_engine_periodic.py will be added here
    # This should be populated with the actual Python script content
  run_periodic_tests.sh: |
    # Content of run_periodic_tests.sh will be added here
    # This should be populated with the actual shell script content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sasya-engine-test-images
  namespace: sasya-arogya
  labels:
    app: sasya-engine
    component: periodic-tests
data:
  # Test images will be added here as base64 encoded data
  # rice_leaf_blight.jpg: <base64-encoded-image-data>
  # apple_leaf_disease.jpg: <base64-encoded-image-data>
  # tomato_disease.jpg: <base64-encoded-image-data>
  # wheat_rust.jpg: <base64-encoded-image-data>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sasya-engine-test-results
  namespace: sasya-arogya
  labels:
    app: sasya-engine
    component: periodic-tests
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2  # Adjust based on your OpenShift storage class
---
apiVersion: v1
kind: Service
metadata:
  name: sasya-engine-service
  namespace: sasya-arogya
  labels:
    app: sasya-engine
    component: engine
spec:
  selector:
    app: sasya-engine
    component: engine
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
