global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sasya-arogya-engine-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s
    metrics_path: /metrics

  # Sasya Engine FastAPI server
  - job_name: 'sasya-engine'
    static_configs:
      - targets: ['host.docker.internal:9080'] # SASYA ENGINE port number
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # System metrics (if node_exporter is added later)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
